name: "GITHUB_ACTION_CI"
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-python@v4
              with:
                  go-version: '3.15'
           - name: Build
             run: go build -v ./...
           - name: Login To DockerHub
             uses: docker/login-action@v1
             with:
                 user: ${{ secrets.DOCKERHUB_USERNAME }}                 
                 password: ${{ secrets.DOCKERTHUB_TOCKEN }}
           - name: build and release to DockerHub
             env:
                 NAME: youngjini
                 REPO: go_file_CI
             run: |
                 docker build -t $REPO .
                 docker tag $REPO:latest $NAME/$REPO:latest
                 docker push $NAME/$REPO:latest
